baseURL = "https://jorrit.co"
languageCode = "en"
title = "Jorrit Gorseman"
theme = "monochrome"
defaultContentLanguage = "en"
enableEmoji = true
disableLanguages = ["zh-tw"]

[build]
writeStats = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
