navbarTitle = 'Jorrit Gorseman'
footer = "Copyright © 2021 by Jorrit Gorseman"

enableZoomingJS = true
enableTOC = true
enableSiteSearch = true
enableMathJax = false

# Codeblock
usePrismJS = false
enablePrismJSLineNo = true
enableCodeCopy = true

# SEO
enableOpenGraph = true
enableTwitterCards = true
author = "kaiiiz"
