title = "Jorrit Gorseman"
theme = "hugo-theme-monochrome"
baseURL = "https://jorrit.co"
languageCode = "en-us"

[build]
writeStats = true

[params]
navbarTitle = "Monochrome"
footer = "Copyright © 2021 by Jorrit Gorseman"
