title = "Jorrit Gorseman"
theme = "monochrome"
baseURL = "https://jorrit.co"
languageCode = "en-us"

[build]
writeStats = true

[params]
navbarTitle = "Jorrit Gorseman"
footer = "Copyright © 2021 by Jorrit Gorseman"