[[navbar]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1
  [[navbar]]
    identifier = "site_settings"
    name = "Site Settings"
    url = "/about/site"
    parent = "about"
    weight = 1
  [[navbar]]
    identifier = "theme_settings"
    name = "Theme Settings"
    url = "/about/theme"
    parent = "about"
    weight = 2
  [[navbar]]
    identifier = "page_settings"
    name = "Page Settings"
    url = "/about/page"
    parent = "about"
    weight = 3
[[navbar]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 2
[[navbar]]
  identifier = "setup"
  name = "Setup"
  url = "/setup/"
  weight = 3
[[navbar]]
  identifier = "changelog"
  name = "Changelog"
  url = "/changelog/"
  weight = 4


