[[navbar]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1
[[navbar]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 3
[[navbar]]
  identifier = "now"
  name = "Now"
  url = "/now/"
  weight = 2
[[navbar]]
  identifier = "Contact"
  name = "Contact"
  url = "/contact/"
  weight = 4


